### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by netdesignate** [james-cube/firefox-bookmarks-deduplicator#2]
Getting a type error as follows - json input file was generated by Firefox 112.0
Same error in Python 3.10 and 3.11

Command line (in WSL Ubuntu 22.04):
`$ python3.11 firefox-bookmarks-deduplicator/firefox_bookmarks_deduplicator/ --file bookmarks-2023-04-13.json --output /mnt/c/DATA/bookmarks_cleaned.json
`

**SNIPPED Many lines of output**
...
9 KUNDA has a duplicate
IDs [9, 15163, 424, 450, 3286, 15578, 15604, 18440, 5595, 10500, 20749, 25654]
Merging id 15163 into 9
Merging id 424 into 9
Merging id 450 into 9
Merging id 3286 into 9
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/mnt/c/DATA/firefox-bookmarks-deduplicator/firefox_bookmarks_deduplicator/__main__.py", line 4, in <module>
    deduplicator.main()
  File "/mnt/c/DATA/firefox-bookmarks-deduplicator/firefox_bookmarks_deduplicator/deduplicator.py", line 23, in main
    deduplicate_and_merge_all(bookmarks_object)
  File "/mnt/c/DATA/firefox-bookmarks-deduplicator/firefox_bookmarks_deduplicator/deduplicator.py", line 13, in deduplicate_and_merge_all
    deduplicate_and_merge(get_bookmarks_from_menu(bookmarks_object))
  File "/mnt/c/DATA/firefox-bookmarks-deduplicator/firefox_bookmarks_deduplicator/deduplicator.py", line 18, in deduplicate_and_merge
    directory_merge(bookmarks)
  File "/mnt/c/DATA/firefox-bookmarks-deduplicator/firefox_bookmarks_deduplicator/deduplicator_utils.py", line 49, in directory_merge
    `for child in dir_to_merge.get("children"):`
**TypeError: 'NoneType' object is not iterable**

**Comment by netdesignate** [comment]
I did get the script to run successfully in the end - the issue above seemed to only occur when there was an entry without any "children" if that helps you in sorting it out.  I manually deleted all entries like that and script ran to completion.  Here's an example of an entry that caused the issue: the "KUNDA" object in the middle of these three entries caused the failure (as an example):

```
                                {
                                    "guid": "dSEbYJtHl4wl",
                                    "title": "My Dyn Account",
                                    "index": 17,
                                    "dateAdded": 1358891465000000,
                                    "lastModified": 1358891465000000,
                                    "id": 3285,
                                    "typeCode": 1,
                                    "iconUri": "fake-favicon-uri:https://account.dyn.com/",
                                    "type": "text/x-moz-place",
                                    "uri": "https://account.dyn.com/"
                                },
                                {
                                    "guid": "jUw-JP-pwcgO",
                                    "title": "**KUNDA**",
                                    "index": 18,
                                    "dateAdded": 1608433520000000,
                                    "lastModified": 1608433520000000,
                                    "id": 3286,
                                    "typeCode": 2,
                                    "type": "text/x-moz-place-container"
                                },
                                {
                                    "guid": "a1H_NPrf88qh",
                                    "title": "Welcome - Yubico",
                                    "index": 19,
                                    "dateAdded": 1358891465000000,
                                    "lastModified": 1358891465000000,
                                    "id": 3287,
                                    "typeCode": 1,
                                    "type": "text/x-moz-place",
                                    "uri": "http://www.yubico.com/"
                                },
```
